# Generated by Django 5.1 on 2024-09-01 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadMap', '0002_step_rename_iduser_roadmap_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Step',
            new_name='Checkpoint',
        ),
    ]
