# Generated by Django 5.1 on 2024-09-02 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_socialmedia_remove_user_id_alter_user_username_and_more'),
        ('roadMap', '0003_rename_step_checkpoint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkpoint',
            old_name='checked',
            new_name='completed',
        ),
        migrations.RemoveField(
            model_name='checkpoint',
            name='idRoadMap',
        ),
        migrations.RemoveField(
            model_name='checkpoint',
            name='step',
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='numberOfCheckpoint',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='numberOfLikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='completionPercentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='mainGoal',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.person'),
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='idRoadmap',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='roadMap.roadmap'),
        ),
    ]
