# Generated by Django 5.1 on 2024-09-01 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadMap', '0003_rename_step_checkpoint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkpoint',
            old_name='idRoadMap',
            new_name='idRoadmap',
        ),
    ]
