# Generated by Django 5.1 on 2024-09-01 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_company_id_remove_person_id_and_more'),
        ('roadMap', '0004_rename_idroadmap_checkpoint_idroadmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmap',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.person'),
        ),
    ]
