# Generated by Django 5.1 on 2024-09-02 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadMap', '0005_alter_roadmap_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkpoint',
            old_name='checked',
            new_name='completed',
        ),
        migrations.RemoveField(
            model_name='checkpoint',
            name='step',
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='numberOfCheckpoint',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='numberOfLikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='idRoadmap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadMap.roadmap'),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='completionPercentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='mainGoal',
            field=models.TextField(),
        ),
    ]
