# Generated by Django 5.1 on 2024-09-08 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_socialmedia_remove_user_id_alter_user_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersocialmedia',
            old_name='socialMedia',
            new_name='idSocialMedia',
        ),
        migrations.RenameField(
            model_name='usersocialmedia',
            old_name='username',
            new_name='idUser',
        ),
    ]
