# Generated by Django 5.1 on 2024-09-01 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_socialmedia_usersocialmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersocialmedia',
            name='socialMedia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.socialmedia'),
        ),
        migrations.AlterField(
            model_name='usersocialmedia',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
