# Generated by Django 5.1 on 2024-09-08 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_socialmedia_usersocialmedia_idsocialmedia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersocialmedia',
            old_name='idSocialMedia',
            new_name='socialMedia',
        ),
        migrations.RenameField(
            model_name='usersocialmedia',
            old_name='idUser',
            new_name='user',
        ),
    ]
