# Generated by Django 5.1 on 2024-09-01 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_usersocialmedia_socialmedia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersocialmedia',
            name='socialMedia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.socialmedia'),
        ),
        migrations.AlterField(
            model_name='usersocialmedia',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
